### ISSUE TITLE
Also delete /data/misc/wifi/networkHistory.txt

### ISSUE THREAD

**Issue by 3v1n0** [Aenadon/WiFi-Fix#1]
[It's used for history of networks](https://android.googlesource.com/platform/frameworks/opt/net/wifi/+/master/service/java/com/android/server/wifi/WifiNetworkHistory.java#59), it might corrupt causing this issue:

```
11-21 11:50:08.990 15567 16078 D WifiConfigStore: "Linksys11060": read to get autoConnectLimited =  0
11-21 11:50:09.153 15567 16078 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: WifiStateMachine
11-21 11:50:09.153 15567 16078 E AndroidRuntime:  at com.android.server.wifi.WifiNetworkHistory.readNetworkHistory(WifiNetworkHistory.java:371)
11-21 11:50:09.153 15567 16078 E AndroidRuntime:  at com.android.server.wifi.WifiConfigManager.readNetworkHistory(WifiConfigManager.java:2120)
11-21 11:50:09.153 15567 16078 E AndroidRuntime:  at com.android.server.wifi.WifiConfigManager.loadConfiguredNetworks(WifiConfigManager.java:1937)
11-21 11:50:09.153 15567 16078 E AndroidRuntime:  at com.android.server.wifi.WifiConfigManager.loadAndEnableAllNetworks(WifiConfigManager.java:527)
11-21 11:50:09.153 15567 16078 E AndroidRuntime:  at com.android.server.wifi.WifiStateMachine$SupplicantStartingState.processMessage(WifiStateMachine.java:5074)
```

**Comment by Aenadon** [comment]
Are there any side effects to this, like losing the passwords or something like that?

**Comment by 3v1n0** [comment]
Nope, that should just be the history of recently used networks... Check your content too.
